# Generated by Django 3.0.6 on 2020-06-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0003_slick'),
    ]

    operations = [
        migrations.AddField(
            model_name='slick',
            name='main_title_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slick',
            name='main_title',
            field=models.CharField(max_length=100),
        ),
    ]
