# Generated by Django 3.0.6 on 2020-06-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0004_auto_20200623_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phonetics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('topic_text', models.TextField()),
            ],
        ),
    ]
