# Generated by Django 3.0.7 on 2020-07-05 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0005_phonetics'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer_one', models.CharField(max_length=255)),
                ('answer_two', models.CharField(max_length=255)),
                ('answer_three', models.CharField(max_length=255)),
                ('answer_four', models.CharField(max_length=255)),
                ('topic', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='english.English')),
            ],
        ),
    ]
