# Generated by Django 3.0.7 on 2020-07-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0007_testphonetics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='english',
            name='lesson_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='phonetics',
            name='lesson_title',
            field=models.CharField(max_length=200),
        ),
    ]
