# Generated by Django 3.0.7 on 2020-07-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0008_auto_20200705_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtest',
            name='question_number',
            field=models.IntegerField(choices=[('one', 1), ('two', 2), ('three', 3), ('four', 4), ('five', 5)], default=1),
            preserve_default=False,
        ),
    ]
