# Generated by Django 3.0.7 on 2020-07-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0010_auto_20200705_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtest',
            name='correcr_answer',
        ),
        migrations.AddField(
            model_name='testtest',
            name='correct_answer',
            field=models.CharField(choices=[('ANSWER_ONE', 'answer_one'), ('ANSWER_TWO', 'answer_two'), ('ANSWER_THREE', 'answer_three'), ('ANSWER_FOUR', 'answer_four')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
