# Generated by Django 3.0.7 on 2020-07-07 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0012_auto_20200705_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='testphonetics',
            name='correct_answer_four',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default='NO', max_length=255),
        ),
        migrations.AddField(
            model_name='testphonetics',
            name='correct_answer_one',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default='NO', max_length=255),
        ),
        migrations.AddField(
            model_name='testphonetics',
            name='correct_answer_three',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default='NO', max_length=255),
        ),
        migrations.AddField(
            model_name='testphonetics',
            name='correct_answer_two',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default='NO', max_length=255),
        ),
        migrations.AddField(
            model_name='testphonetics',
            name='question_number',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testphonetics',
            name='topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='english.English'),
        ),
    ]
