# Generated by Django 3.0.7 on 2020-07-07 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0013_auto_20200707_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testphonetics',
            name='answer_four',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testphonetics',
            name='answer_one',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testphonetics',
            name='answer_three',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testphonetics',
            name='answer_two',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testphonetics',
            name='topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='english.Phonetics'),
        ),
    ]
