# Generated by Django 3.0.7 on 2020-07-08 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0017_english_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='english',
            old_name='video',
            new_name='video_url',
        ),
    ]
