# Generated by Django 3.0.7 on 2020-07-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0018_auto_20200708_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonetics',
            name='video_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
