# Generated by Django 3.0.7 on 2020-07-08 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0019_phonetics_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtest',
            name='question_number',
        ),
    ]
