# Generated by Django 3.0.7 on 2020-07-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0021_testtest_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtest',
            name='check_box',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
