# Generated by Django 3.0.7 on 2020-07-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0022_testtest_check_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testphonetics',
            name='correct_answer_four',
        ),
        migrations.RemoveField(
            model_name='testphonetics',
            name='correct_answer_one',
        ),
        migrations.RemoveField(
            model_name='testphonetics',
            name='correct_answer_three',
        ),
        migrations.RemoveField(
            model_name='testphonetics',
            name='correct_answer_two',
        ),
        migrations.RemoveField(
            model_name='testtest',
            name='check_box',
        ),
        migrations.RemoveField(
            model_name='testtest',
            name='correct_answer_four',
        ),
        migrations.RemoveField(
            model_name='testtest',
            name='correct_answer_one',
        ),
        migrations.RemoveField(
            model_name='testtest',
            name='correct_answer_three',
        ),
        migrations.RemoveField(
            model_name='testtest',
            name='correct_answer_two',
        ),
        migrations.AddField(
            model_name='testphonetics',
            name='check_box_four',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testphonetics',
            name='check_box_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testphonetics',
            name='check_box_three',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testphonetics',
            name='check_box_two',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testtest',
            name='check_box_four',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testtest',
            name='check_box_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testtest',
            name='check_box_three',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testtest',
            name='check_box_two',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testtest',
            name='answer_four',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testtest',
            name='answer_one',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testtest',
            name='answer_three',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testtest',
            name='answer_two',
            field=models.TextField(),
        ),
    ]
