# Generated by Django 3.0.7 on 2020-07-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0023_auto_20200708_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testphonetics',
            old_name='check_box_four',
            new_name='correct_answer_four',
        ),
        migrations.RenameField(
            model_name='testphonetics',
            old_name='check_box_one',
            new_name='correct_answer_one',
        ),
        migrations.RenameField(
            model_name='testphonetics',
            old_name='check_box_three',
            new_name='correct_answer_three',
        ),
        migrations.RenameField(
            model_name='testphonetics',
            old_name='check_box_two',
            new_name='correct_answer_two',
        ),
        migrations.RenameField(
            model_name='testtest',
            old_name='check_box_four',
            new_name='correct_answer_four',
        ),
        migrations.RenameField(
            model_name='testtest',
            old_name='check_box_one',
            new_name='correct_answer_one',
        ),
        migrations.RenameField(
            model_name='testtest',
            old_name='check_box_three',
            new_name='correct_answer_three',
        ),
        migrations.RenameField(
            model_name='testtest',
            old_name='check_box_two',
            new_name='correct_answer_two',
        ),
    ]
