# Generated by Django 3.0.7 on 2020-07-08 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0025_dictionaryfirst'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionaryfirst',
            old_name='word_ninne',
            new_name='word_nine',
        ),
    ]
