# Generated by Django 3.0.7 on 2020-07-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0027_dictionaryfirst_translation_word_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryfirst',
            name='translation_word_eight',
            field=models.CharField(default='    -    ', max_length=50),
        ),
        migrations.AddField(
            model_name='dictionaryfirst',
            name='translation_word_five',
            field=models.CharField(default='    -    ', max_length=50),
        ),
        migrations.AddField(
            model_name='dictionaryfirst',
            name='translation_word_four',
            field=models.CharField(default='    -    ', max_length=50),
        ),
        migrations.AddField(
            model_name='dictionaryfirst',
            name='translation_word_nine',
            field=models.CharField(default='    -    ', max_length=50),
        ),
        migrations.AddField(
            model_name='dictionaryfirst',
            name='translation_word_seven',
            field=models.CharField(default='    -    ', max_length=50),
        ),
        migrations.AddField(
            model_name='dictionaryfirst',
            name='translation_word_six',
            field=models.CharField(default='    -    ', max_length=50),
        ),
        migrations.AddField(
            model_name='dictionaryfirst',
            name='translation_word_ten',
            field=models.CharField(default='    -    ', max_length=50),
        ),
        migrations.AddField(
            model_name='dictionaryfirst',
            name='translation_word_three',
            field=models.CharField(default='    -    ', max_length=50),
        ),
        migrations.AddField(
            model_name='dictionaryfirst',
            name='translation_word_two',
            field=models.CharField(default='    -    ', max_length=50),
        ),
    ]
