# Generated by Django 3.0.7 on 2020-07-09 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0028_auto_20200709_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryThird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(max_length=200)),
                ('word_one', models.CharField(max_length=50)),
                ('translation_word_one', models.CharField(default='    -    ', max_length=50)),
                ('word_two', models.CharField(max_length=50)),
                ('translation_word_two', models.CharField(default='    -    ', max_length=50)),
                ('word_three', models.CharField(max_length=50)),
                ('translation_word_three', models.CharField(default='    -    ', max_length=50)),
                ('word_four', models.CharField(max_length=50)),
                ('translation_word_four', models.CharField(default='    -    ', max_length=50)),
                ('word_five', models.CharField(max_length=50)),
                ('translation_word_five', models.CharField(default='    -    ', max_length=50)),
                ('word_six', models.CharField(max_length=50)),
                ('translation_word_six', models.CharField(default='    -    ', max_length=50)),
                ('word_seven', models.CharField(max_length=50)),
                ('translation_word_seven', models.CharField(default='    -    ', max_length=50)),
                ('word_eight', models.CharField(max_length=50)),
                ('translation_word_eight', models.CharField(default='    -    ', max_length=50)),
                ('word_nine', models.CharField(max_length=50)),
                ('translation_word_nine', models.CharField(default='    -    ', max_length=50)),
                ('word_ten', models.CharField(max_length=50)),
                ('translation_word_ten', models.CharField(default='    -    ', max_length=50)),
                ('topic', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='english.Phonetics')),
            ],
        ),
        migrations.CreateModel(
            name='DictionarySecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(max_length=200)),
                ('word_one', models.CharField(max_length=50)),
                ('translation_word_one', models.CharField(default='    -    ', max_length=50)),
                ('word_two', models.CharField(max_length=50)),
                ('translation_word_two', models.CharField(default='    -    ', max_length=50)),
                ('word_three', models.CharField(max_length=50)),
                ('translation_word_three', models.CharField(default='    -    ', max_length=50)),
                ('word_four', models.CharField(max_length=50)),
                ('translation_word_four', models.CharField(default='    -    ', max_length=50)),
                ('word_five', models.CharField(max_length=50)),
                ('translation_word_five', models.CharField(default='    -    ', max_length=50)),
                ('word_six', models.CharField(max_length=50)),
                ('translation_word_six', models.CharField(default='    -    ', max_length=50)),
                ('word_seven', models.CharField(max_length=50)),
                ('translation_word_seven', models.CharField(default='    -    ', max_length=50)),
                ('word_eight', models.CharField(max_length=50)),
                ('translation_word_eight', models.CharField(default='    -    ', max_length=50)),
                ('word_nine', models.CharField(max_length=50)),
                ('translation_word_nine', models.CharField(default='    -    ', max_length=50)),
                ('word_ten', models.CharField(max_length=50)),
                ('translation_word_ten', models.CharField(default='    -    ', max_length=50)),
                ('topic', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='english.Phonetics')),
            ],
        ),
    ]
