# Generated by Django 3.0.7 on 2020-07-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0030_auto_20200709_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionaryfirst',
            name='translation_word_eight',
        ),
        migrations.RemoveField(
            model_name='dictionaryfirst',
            name='translation_word_nine',
        ),
        migrations.RemoveField(
            model_name='dictionaryfirst',
            name='translation_word_seven',
        ),
        migrations.RemoveField(
            model_name='dictionaryfirst',
            name='translation_word_six',
        ),
        migrations.RemoveField(
            model_name='dictionaryfirst',
            name='translation_word_ten',
        ),
        migrations.RemoveField(
            model_name='dictionaryfirst',
            name='word_eight',
        ),
        migrations.RemoveField(
            model_name='dictionaryfirst',
            name='word_nine',
        ),
        migrations.RemoveField(
            model_name='dictionaryfirst',
            name='word_seven',
        ),
        migrations.RemoveField(
            model_name='dictionaryfirst',
            name='word_six',
        ),
        migrations.RemoveField(
            model_name='dictionaryfirst',
            name='word_ten',
        ),
        migrations.RemoveField(
            model_name='dictionarysecond',
            name='translation_word_eight',
        ),
        migrations.RemoveField(
            model_name='dictionarysecond',
            name='translation_word_nine',
        ),
        migrations.RemoveField(
            model_name='dictionarysecond',
            name='translation_word_seven',
        ),
        migrations.RemoveField(
            model_name='dictionarysecond',
            name='translation_word_six',
        ),
        migrations.RemoveField(
            model_name='dictionarysecond',
            name='translation_word_ten',
        ),
        migrations.RemoveField(
            model_name='dictionarysecond',
            name='word_eight',
        ),
        migrations.RemoveField(
            model_name='dictionarysecond',
            name='word_nine',
        ),
        migrations.RemoveField(
            model_name='dictionarysecond',
            name='word_seven',
        ),
        migrations.RemoveField(
            model_name='dictionarysecond',
            name='word_six',
        ),
        migrations.RemoveField(
            model_name='dictionarysecond',
            name='word_ten',
        ),
    ]
