# Generated by Django 3.0.7 on 2020-07-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0034_сurriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonetics',
            name='length_of_questions',
            field=models.IntegerField(default=0),
        ),
    ]
