# Generated by Django 3.0.7 on 2020-07-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0035_phonetics_length_of_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonetics',
            name='res_length_of_questions',
            field=models.IntegerField(default=0),
        ),
    ]
