# Generated by Django 3.0.7 on 2020-07-15 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0036_phonetics_res_length_of_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWorkPhonetics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_one', models.CharField(max_length=200)),
                ('semtence_word_one', models.CharField(max_length=255)),
                ('topic', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='english.Phonetics')),
            ],
        ),
    ]
