# Generated by Django 3.0.7 on 2020-07-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0038_homeworkphonetics_complete_semtence_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkphonetics',
            name='translation_one',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
