# Generated by Django 3.0.7 on 2020-07-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0039_homeworkphonetics_translation_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkphonetics',
            name='lesson_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
