# Generated by Django 3.0.7 on 2020-07-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0040_homeworkphonetics_lesson_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='dictionaryfirst',
            name='translation_word_five',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionaryfirst',
            name='translation_word_four',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionaryfirst',
            name='translation_word_one',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionaryfirst',
            name='translation_word_three',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionaryfirst',
            name='translation_word_two',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionaryfirst',
            name='word_five',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionaryfirst',
            name='word_four',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionaryfirst',
            name='word_one',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionaryfirst',
            name='word_three',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionaryfirst',
            name='word_two',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarfirst',
            name='translation_word_eight',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarfirst',
            name='translation_word_nine',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarfirst',
            name='translation_word_seven',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarfirst',
            name='translation_word_six',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarfirst',
            name='translation_word_ten',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarfirst',
            name='word_eight',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarfirst',
            name='word_nine',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarfirst',
            name='word_seven',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarfirst',
            name='word_six',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarfirst',
            name='word_ten',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarsecond',
            name='translation_word_eight',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarsecond',
            name='translation_word_nine',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarsecond',
            name='translation_word_seven',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarsecond',
            name='translation_word_six',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarsecond',
            name='translation_word_ten',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarsecond',
            name='word_eight',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarsecond',
            name='word_nine',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarsecond',
            name='word_seven',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarsecond',
            name='word_six',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarsecond',
            name='word_ten',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarthird',
            name='translation_word_eight',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarthird',
            name='translation_word_nine',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarthird',
            name='translation_word_seven',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarthird',
            name='translation_word_six',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarthird',
            name='translation_word_ten',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarthird',
            name='word_eight',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarthird',
            name='word_nine',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarthird',
            name='word_seven',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarthird',
            name='word_six',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarthird',
            name='word_ten',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarysecond',
            name='translation_word_five',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarysecond',
            name='translation_word_four',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarysecond',
            name='translation_word_one',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarysecond',
            name='translation_word_three',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarysecond',
            name='translation_word_two',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarysecond',
            name='word_five',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarysecond',
            name='word_four',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarysecond',
            name='word_one',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarysecond',
            name='word_three',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarysecond',
            name='word_two',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarythird',
            name='translation_word_five',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarythird',
            name='translation_word_four',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarythird',
            name='translation_word_one',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarythird',
            name='translation_word_three',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarythird',
            name='translation_word_two',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarythird',
            name='word_five',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarythird',
            name='word_four',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarythird',
            name='word_one',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarythird',
            name='word_three',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarythird',
            name='word_two',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='english',
            name='img',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='english',
            name='lesson_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='english',
            name='topic_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='english',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='homeworkphonetics',
            name='complete_semtence_one',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='homeworkphonetics',
            name='semtence_word_one',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='homeworkphonetics',
            name='translation_one',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='homeworkphonetics',
            name='word_one',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='phonetics',
            name='img',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='phonetics',
            name='topic_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='phonetics',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
