# Generated by Django 3.0.7 on 2020-07-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0041_auto_20200716_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkphonetics',
            name='semtence_word_two',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='semtence_word_two_two',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='translation_two',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='two',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='word_two',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
