# Generated by Django 3.0.7 on 2020-07-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0042_auto_20200716_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkphonetics',
            name='complete_semtence_five',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='complete_semtence_four',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='complete_semtence_three',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='semtence_word_five',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='semtence_word_four',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='semtence_word_three',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='translation_five',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='translation_four',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='translation_three',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='word_five',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='word_five_two',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='word_four',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='word_four_two',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='word_three',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='word_three_two',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
