# Generated by Django 3.0.7 on 2020-07-16 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0043_auto_20200716_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeworkphonetics',
            old_name='two',
            new_name='complete_semtence_two',
        ),
    ]
