# Generated by Django 3.0.7 on 2020-07-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0044_auto_20200716_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkphonetics',
            name='scramble_five_four',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='scramble_five_one',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='scramble_five_three',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='scramble_five_two',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='scramble_four_four',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='scramble_four_one',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='scramble_four_three',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='scramble_four_two',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='scramble_one_four',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='scramble_one_one',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='scramble_one_three',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='scramble_one_two',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='scramble_semtence_five',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='scramble_semtence_four',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='scramble_semtence_one',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='scramble_semtence_three',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='scramble_semtence_two',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='scramble_three_four',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='scramble_three_one',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='scramble_three_three',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='scramble_three_two',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='scramble_two_four',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='scramble_two_one',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='scramble_two_three',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='scramble_two_two',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
