# Generated by Django 3.0.7 on 2020-07-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0045_auto_20200716_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeworkphonetics',
            old_name='word_five',
            new_name='word_1',
        ),
        migrations.RenameField(
            model_name='homeworkphonetics',
            old_name='word_five_two',
            new_name='word_2',
        ),
        migrations.RenameField(
            model_name='homeworkphonetics',
            old_name='word_four',
            new_name='word_3',
        ),
        migrations.RenameField(
            model_name='homeworkphonetics',
            old_name='word_four_two',
            new_name='word_4',
        ),
        migrations.RenameField(
            model_name='homeworkphonetics',
            old_name='word_one',
            new_name='word_5',
        ),
        migrations.RenameField(
            model_name='homeworkphonetics',
            old_name='word_three',
            new_name='word_6',
        ),
        migrations.RenameField(
            model_name='homeworkphonetics',
            old_name='word_three_two',
            new_name='word_7',
        ),
        migrations.RenameField(
            model_name='homeworkphonetics',
            old_name='word_two',
            new_name='word_8',
        ),
    ]
