# Generated by Django 3.0.7 on 2020-07-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0046_auto_20200716_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkphonetics',
            name='main_sentence_five',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='main_sentence_four',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='main_sentence_one',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='main_sentence_three',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='main_sentence_translation_five',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='main_sentence_translation_four',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='main_sentence_translation_one',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='main_sentence_translation_three',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='main_sentence_translation_two',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='main_sentence_two',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
