# Generated by Django 3.0.7 on 2020-07-22 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0047_auto_20200719_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='english',
            name='affirmative',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='english',
            name='interrogative',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='english',
            name='negative',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='english',
            name='plural',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='english',
            name='plural_negative',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='english',
            name='plural_question',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='english',
            name='singular',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='english',
            name='singular_negative',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='english',
            name='singular_question',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarfirst',
            name='topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='english.English'),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarsecond',
            name='topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='english.English'),
        ),
        migrations.AlterField(
            model_name='dictionarygrammarthird',
            name='topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='english.English'),
        ),
    ]
