# Generated by Django 3.0.7 on 2020-07-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0048_auto_20200722_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='english',
            name='topic_text_two',
            field=models.TextField(blank=True),
        ),
    ]
