# Generated by Django 3.0.7 on 2020-07-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0050_homeworkgrammar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slick',
            name='img_1',
            field=models.FileField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='slick',
            name='img_2',
            field=models.FileField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='slick',
            name='img_3',
            field=models.FileField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='slick',
            name='img_4',
            field=models.FileField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='slick',
            name='img_5',
            field=models.FileField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='slick',
            name='img_6',
            field=models.FileField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='slick',
            name='img_7',
            field=models.FileField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='slick',
            name='main_img',
            field=models.FileField(upload_to='pics'),
        ),
    ]
