# Generated by Django 3.0.7 on 2020-07-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0051_auto_20200725_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='сurriculum',
            name='grammar',
            field=models.FileField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='сurriculum',
            name='grammar_img',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='сurriculum',
            name='notebook',
            field=models.FileField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='сurriculum',
            name='notebook_img',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='сurriculum',
            name='phonetics',
            field=models.FileField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='сurriculum',
            name='phonetics_img',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='сurriculum',
            name='practice',
            field=models.FileField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='сurriculum',
            name='practice_img',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='сurriculum',
            name='proverb',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='сurriculum',
            name='question',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='сurriculum',
            name='radio',
            field=models.FileField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='сurriculum',
            name='radio_img',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='сurriculum',
            name='repeat',
            field=models.FileField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='сurriculum',
            name='repeat_img',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='сurriculum',
            name='start',
            field=models.FileField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='сurriculum',
            name='words',
            field=models.FileField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='сurriculum',
            name='words_img',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='сurriculum',
            name='curriculum_text',
            field=models.TextField(blank=True),
        ),
    ]
