# Generated by Django 3.0.7 on 2020-07-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0052_auto_20200727_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сurriculum',
            name='notebook',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
