# Generated by Django 3.0.7 on 2020-07-27 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0053_auto_20200727_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сurriculum',
            name='grammar',
        ),
        migrations.RemoveField(
            model_name='сurriculum',
            name='grammar_img',
        ),
        migrations.RemoveField(
            model_name='сurriculum',
            name='notebook',
        ),
        migrations.RemoveField(
            model_name='сurriculum',
            name='notebook_img',
        ),
        migrations.RemoveField(
            model_name='сurriculum',
            name='phonetics',
        ),
        migrations.RemoveField(
            model_name='сurriculum',
            name='phonetics_img',
        ),
        migrations.RemoveField(
            model_name='сurriculum',
            name='practice',
        ),
        migrations.RemoveField(
            model_name='сurriculum',
            name='practice_img',
        ),
        migrations.RemoveField(
            model_name='сurriculum',
            name='proverb',
        ),
        migrations.RemoveField(
            model_name='сurriculum',
            name='question',
        ),
        migrations.RemoveField(
            model_name='сurriculum',
            name='radio',
        ),
        migrations.RemoveField(
            model_name='сurriculum',
            name='radio_img',
        ),
        migrations.RemoveField(
            model_name='сurriculum',
            name='repeat',
        ),
        migrations.RemoveField(
            model_name='сurriculum',
            name='repeat_img',
        ),
        migrations.RemoveField(
            model_name='сurriculum',
            name='start',
        ),
        migrations.RemoveField(
            model_name='сurriculum',
            name='words',
        ),
        migrations.RemoveField(
            model_name='сurriculum',
            name='words_img',
        ),
    ]
