# Generated by Django 3.0.7 on 2020-07-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0054_auto_20200727_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='сurriculum',
            name='start',
            field=models.TextField(blank=True),
        ),
    ]
