# Generated by Django 3.0.7 on 2020-07-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0055_сurriculum_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='сurriculum',
            name='question',
            field=models.TextField(blank=True),
        ),
    ]
