# Generated by Django 3.0.7 on 2020-07-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0057_сurriculum_notebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='сurriculum',
            name='phonetics',
            field=models.TextField(blank=True),
        ),
    ]
