# Generated by Django 3.0.7 on 2020-07-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0058_сurriculum_phonetics'),
    ]

    operations = [
        migrations.AddField(
            model_name='сurriculum',
            name='grammar',
            field=models.TextField(blank=True),
        ),
    ]
