# Generated by Django 3.0.7 on 2020-07-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0059_сurriculum_grammar'),
    ]

    operations = [
        migrations.AddField(
            model_name='сurriculum',
            name='repeat',
            field=models.TextField(blank=True),
        ),
    ]
