# Generated by Django 3.0.7 on 2020-07-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0060_сurriculum_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='сurriculum',
            name='words',
            field=models.TextField(blank=True),
        ),
    ]
