# Generated by Django 3.0.7 on 2020-07-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0061_сurriculum_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='сurriculum',
            name='practice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='сurriculum',
            name='radio',
            field=models.TextField(blank=True),
        ),
    ]
