# Generated by Django 3.0.7 on 2020-07-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0063_auto_20200728_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkphonetics',
            name='speech_sentence_five',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='speech_sentence_four',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='speech_sentence_one',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='speech_sentence_three',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homeworkphonetics',
            name='speech_sentence_two',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
