# Generated by Django 3.0.7 on 2020-08-07 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0067_auto_20200807_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markphonetics',
            name='topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='english.Phonetics'),
        ),
    ]
