# Generated by Django 3.0.7 on 2020-08-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0068_auto_20200807_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='english',
            name='length_of_questions',
            field=models.IntegerField(default=0),
        ),
    ]
